src/DaZuiWang/DaZuiWang/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from views import login_view,logout_view,main_view,register_view,address
from stores import views as stores_view
from bootstrap import views as test_view
import django_braintree
admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
#admin.autodiscover()

urlpatterns = patterns('',
    
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$',login_view,name='login'),
    url(r'^accounts/address$',address,name='address'),
    url(r'^accounts/logout/$',logout_view,name='logout'),
    url(r'^accounts/register/$',register_view,name='register'),
    url(r'^stores/', include('stores.urls')),
    url(r'', include('django_braintree.urls')),
    url(r'^$',test_view.main,name='main'),


    # url(r'^test/gmap3/$',test_view.gmap3,name='gmap3'),
    # url(r'^test/gmap3/$',test_view.o,name='gmap3'),
    #url(r'^test/search/$',test_view.search,name='search'),
    
    #url(r'^test/intro/$',test_view.intro,name='intro')
    
    )

#url(r'^main/$', main_view), 
    #url(r'^main/RestaurantAll',Cuisine_view.getAllRestaurant, name="getAllRestaurant"),
#url(r'^stores/', stores_view.index,name='index'),
    #url(r'^stores/cart/$',stores_view.cart,name='cart'),
    #url(r'^add_to_cart/(?P<product_id>\d+)/$', stores_view.cart, name='add_to_cart'),
    #get cuisines for resturant
    #url(r'cuisine/$',Cuisine_view.getCuisineForOneRestaurant,name="getCuisine")
#  DaZuiWang.Cuisine.views.getCuisineForOneRestaurant
    # Examples:s
    # url(r'^$', 'DaZuiWang.views.home', name='home'),
    # url(r'^DaZuiWang/', include('DaZuiWang.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    #url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/DaZuiWang/stores/urls.py
'''
Created on 2013-8-31

@author: samsung
'''
'''
Created on 2013-8-22

@author: samsung
'''
from django.conf.urls import patterns, url

from stores import views


urlpatterns = patterns('',
    url(r'^$', views.index_stores_all, name='index'),
    url(r'^person/$',views.person,name='person'),
    url(r'^store/$',views.store,name='store'),
    url(r'^intro/$',views.intro,name='intro'),
    url(r'^order/$',views.order,name='order'),
    url(r'^order/$',views.order,name='agree_order'),
    url(r'^order/$',views.order,name='cancel_order'),
    url(r'^order/$',views.order,name='finish_order'),
    
    url(r'^storeorder/$',views.storeorder,name='storeorder'),
    
    url(r'^searchTag/$',views.searchTag,name='searchTag'),
    url(r'^search/$',views.search,name='search'),
    
    url(r'^searchMain/$',views.searchMain,name='searchMain'), 

    url(r'all_products/$',views.all_products,name='all_products'),
    url(r'^registrhtml/$',views.registerHtml,name='registerHtml'),
    url(r'(?P<store_id>\d+)/$',views.index_all,name='store_index'),
    url(r'products/',views.index_store_products,name='products'),
    url(r'get_product/',views.get_product,name='get_product'),
    url(r'^add_to_cart/$', views.cart, name='add_to_cart'),
    url(r'^remove_from_cart/$', views.remove_from_cart, name='remove_from_cart'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^checkout_cart/$', views.checkout_cart, name='checkout_cart'),
    url(r'^confirm_order/(?P<order_id>\d+)/$', views.confirm_order, name='confirm_order'),
    url(r'^delete_order/(?P<order_id>\d+)/$', views.delete_order, name='delete_order'),
    url(r'^past_orders/$', views.past_orders, name='past_orders'),

    )
#url(r'^add_to_cart/(?P<product_id>\d+)/$', views.cart, name='add_to_cart'),
#url(r'^remove_from_cart/(?P<product_id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),

src/DaZuiWang/stores/models.py
#! -*- coding:utf-8 -*- 
from django.db import models
# Create your models here.
from datetime import date

from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
import locale

locale.setlocale(locale.LC_ALL, '')


class Store(models.Model):
    name = models.CharField(max_length=255,verbose_name="名称")
    image = models.ImageField(upload_to='store_images')
    ads_image=models.ImageField(upload_to='store_images',verbose_name='宣传照片（尺寸:880×230）')
    description=models.TextField()
    store_quantitiy=models.IntegerField()
    telphone=models.CharField(max_length=255,verbose_name="电话")
    
    lat=models.DecimalField(max_digits=10,decimal_places=6)
    lon=models.DecimalField(max_digits=10,decimal_places=6)
    def __unicode__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to='product_images')
    quantity = models.IntegerField()
    store = models.ForeignKey(Store)
    cuisine=models.CharField(max_length=50, choices=[(t,t) for t in ('chinese', 'europe', 'japan', 'franch','italy','tailand')],
                                        null=True)
    def price_string(self):
         print self.price;
         return self.price; 
         return locale.currency(self.price, grouping=True)
    
    def __unicode__(self):
        return self.name

class ProductQuantities(models.Model):
    product = models.ForeignKey('Product')
    order = models.ForeignKey('Order')
    quantity = models.IntegerField()
    def product_price(self):
        print "nihs"
        print "hehe "+str(self.product.price)
        return self.product.price*self.quantity
class Order(models.Model):

    user = models.ForeignKey(User)
    products = models.ManyToManyField(Product, through=ProductQuantities)
    store = models.ForeignKey(Store)

    name_on_card = models.CharField(max_length=255, null=True)
    credit_card_type = models.CharField(max_length=50, 
                                        choices=[(t,t) for t in ('Visa', 'MasterCard', 'American Express', 'Discover')],
                                        null=True)
    credit_card_number = models.CharField(max_length=20, null=True)
    
    security_number = models.CharField(max_length=4, null=True)
    expiration_month = models.IntegerField(choices=[(m, m) for m in xrange(1,13)], null=True)

    _current_year = date.today().year
    expiration_year = models.IntegerField(choices=[(y, y) for y in xrange(_current_year, _current_year + 20)], null=True)
    address = models.CharField(max_length=255, null=True)
    city = models.CharField(max_length=255, null=True)
    state = models.CharField(max_length=255, null=True)
    zip_code = models.CharField(max_length=255, null=True)
    phone_number = models.CharField(max_length=10, null=True)

    ordered_on = models.DateTimeField(null=True)
    shipped_on = models.DateTimeField(null=True)
    send_time=models.DateTimeField(null=True)
    pay_way = models.CharField(max_length=50, 
                                        choices=[(t,t) for t in ('pay_offline', 'pay_online')],
                                        null=True)
    notes=models.CharField(max_length=255, null=True)
    status=models.CharField(max_length=50, 
                                        choices=[(t,t) for t in ('ing','accepted', 'finished', 'unfinished')],
                                        null=True)
    def cancel_order(self):
        try:
            self.status="unfinished"
            self.save()
        except Exception, e:
            print e
    def agree_order(self):
        try:
            self.status="accepted"
            self.save()
        except Exception, e:
            print e
    def finish_order(self):
        try:
            self.status="finished"
            self.save()
        except Exception, e:
            print e
    def total_num(self):
        t=0
        for pq in self.productquantities_set.all():
            t+=pq.quantity
        return t
    def total(self):
        t=0
#        print "total"
        for pq in self.productquantities_set.all():
            t+=pq.product.price*pq.quantity
        return t
        #return locale.currency(t, grouping=True)
       

    def add_product(self, product):
        product_quantity = None
        try:
            product_quantity = ProductQuantities.objects.get(order=self, product=product)
            product_quantity.quantity += 1
            product_quantity.save()
        except ProductQuantities.DoesNotExist:
            product_quantity = ProductQuantities.objects.create(order=self, product=product, quantity=1)

    def remove_product(self, product):
        try:
            product_quantity = ProductQuantities.objects.get(order=self, product=product)
            product_quantity.quantity -= 1
            if product_quantity.quantity > 0:
                product_quantity.save()
            else:
                product_quantity.delete()
        except ProductQuantities.DoesNotExist:
            pass

    @classmethod
    def get_cart(cls, store, user):
        cart, created = cls.objects.get_or_create(store=store, user=user, ordered_on__isnull=True)
        return cart

   
    def __unicode__(self):
        return "%s %s - %s" % (self.id, self.user.username, self.ordered_on)

def main():
    print locale.currency(12, grouping=True)
    print "1"
if __name__ == '__main__':
    main()

src/DaZuiWang/stores/forms.py
'''
Created on 2013-8-22

@author: samsung
'''
from django import forms

from stores import models


class CheckoutForm(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ['credit_card_type','credit_card_number', 'security_number', 'expiration_month', 'expiration_year', 'address', 'city', 'state', 'zip_code', 'phone_number']

src/DaZuiWang/stores/templates/cart.html
<link href="http://cdnjs.bootcss.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap.min.css" rel="stylesheet">
<script  src="http://cdnjs.bootcss.com/ajax/libs/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>   

<link href="http://cdnjs.bootcss.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap.css" rel="stylesheet">
<style type="text/css">
.ui-co-label {
position: relative;
padding-left: 25px;
width: 82%;
color: #444;
line-height: 28px;
margin: 0 0 0 0;
text-align:right;
float: left;
}
.coolist-item.current {
	background: #f1f1f1;
}
.coolist-item {
	padding: 10px 10px;
}
.divOver{
	background:#eff8fe;
} 
.cooverlay-list {
	list-style:none;
	margin:0px;
} 
.coli-action{
	float: left;
}
.ui-co-radio{
	float: left;
}
.addr_sav{
	display: none;
}
.addr_ccl{
	display: none;
}
.addr_mod{
	display: none;
}
.addr{
	float: left;
}
.cart-actions{
	float: left;
}
</style>
<script type="text/javascript">

$(function(){
	// 圆角
	$('#so_addr').hide();

	$('.companel-edit').bind('click',function(event) {
		/* Act on the event */
		$('#so_addr').slideToggle(500);
		$('#addr_div').slideToggle(500);

	});
	//发送请求 获取地址列表
	// alert("te");
	var id=1;
	$.get("{% url 'address' %}", function(data) {
		/*optional stuff to do after success */
		//var rdata=JSON.parse(data);
		// alert(data.address);
		$.each(data, function(index, val) {
			// $('#addr_list').append(data.address);
			// var t="<li class='addr_item coolist-item clearfix current'><input id='3280347' class='ui-co-radio' type='radio' name='optionAddress' checked='checked'><label class='ui-co-label' for='3280347' data-id="+id.toString()+">";
			if(index=="address"){
				$('#addr_list').append("<li class='addr_item coolist-item clearfix current '><input id='3280347' class='ui-co-radio' type='radio' name='optionAddress' checked='checked'><label class='ui-co-label' for='3280347' data-id="+id.toString()+">"+"<span class='addr'>"+val+"</span>"+"</label>"+"<span class='addr_act coli-action'><a class='addr_mod modify'>修改</a><a class='addr_del del'>×</a><a class='addr_sav save'>保存</a><a class='addr_ccl cancel'>取消</a></span></li>");
			}else{
				$('#addr_list').append("<li class='addr_item coolist-item clearfix '><input id='3280347' class='ui-co-radio' type='radio' name='optionAddress'><label class='ui-co-label' for='3280347' data-id="+id.toString()+">"+"<span class='addr'>"+val+"</span>"+"</label>"+"<span class='addr_act coli-action'><a class='addr_mod modify'>修改</a><a class='addr_del del'>×</a><a class='addr_sav save'>保存</a><a class='addr_ccl cancel'>取消</a></span></li>");
			}
			
			
		});
		$('#addr_info').html(data.address);

		$('.addr_item').bind('click',  function(event) {
			/* Act on the event */
			$('.addr_item').removeClass('current');
			$(this).addClass('current');
		});
		// $('.companel-edit').bind('click',function(event) {
		// 	/* Act on the event */
		// 	$('#so_addr').slideToggle(500);
		// 	$('#addr_div').slideToggle(500);

		// });
		$(".addr_item").mouseenter(function(event) {
			/* Act on the event */
			$(this).find('.addr_mod').show(22);
		})
		$(".addr_item").mouseleave(function(event) {
			/* Act on the event */
			$(this).find('.addr_mod').hide(22);
		});
		$('#pay_offline').bind('click', function() {
			/* Act on the event */
			$(this).addClass('btn-danger');
			$('#pay_online').removeClass('btn-danger');
		});

		$('#pay_online').bind('click', function(event) {

			$(this).addClass('btn-danger');
			$('#pay_offline').removeClass('btn-danger');
		});
		$('#send_time').datetimepicker({
			format: 'yyyy-mm-dd hh:ii',
			startView: 'hour',
			minView:'hour',
			language:'zh-CN'
		});
		$(".addr_item").mouseenter(function(event) {
			/* Act on the event */
			$(this).find('.addr_mod').show(22);
		})
		$(".addr_item").mouseleave(function(event) {
			/* Act on the event */
			$(this).find('.addr_mod').hide(22);
		});

		var today=new Date();
		var m=today.getMonth()+1
		var to=today.getFullYear()+'-'+m+'-'+ today.getDate()+' '+today.getHours()+':'+today.getMinutes();
		// alert(to);
		$('#send_time').datetimepicker('setStartDate', to);
		var par = $('#checkout-form');
		$(par).hide();
		/*变色*/
		
	});
	$('#addr_confirm').bind('click', function(event) {
		/* Act on the event */
		var addr=$('input[name=optionAddress]:checked').parent().find('label').find('.addr').text();
		$('#addr_info').html(addr);
		// $('.companel-edit').bind('click',function(event) {
		// 	/* Act on the event */
		// 	$('#so_addr').slideToggle(500);
		// 	$('#addr_div').slideToggle(500);

		// });
		$('#so_addr').slideToggle(500);
		$('#addr_div').slideToggle(500);


	});
	$('.comodule-panel').hover(function() {
		/* Stuff to do when the mouse enters the element */
		$(this).addClass('divOver');
	}, function() {
		/* Stuff to do when the mouse leaves the element */
		$(this).removeClass('divOver');
	});

		//支付方式
	// $(".addr_item").hover(function() {
	// 	/* Stuff to do when the mouse enters the element */
	
	// 	$(this).find('.addr_mod').slideToggle(22);
	// }, function() {
	// 	/* Stuff to do when the mouse leaves the element */
	// 	$(this).find('.addr_mod').hide(22);
	// });
	
	$('#pay_offline').bind('click', function() {
		/* Act on the event */
		$(this).addClass('btn-danger');
		$('#pay_online').removeClass('btn-danger');
	});

	$('#pay_online').bind('click', function(event) {
		
		$(this).addClass('btn-danger');
		$('#pay_offline').removeClass('btn-danger');
	});
	$('#send_time').datetimepicker({
		 format: 'yyyy-mm-dd hh:ii',
		 startView: 'hour',
		 minView:'hour',
		 language:'zh-CN'
	 });
	// 发送时间
	
	
	$('.remove-from-cart').on("click",function(e){
		 //alert($( this ).attr("productid" ));
		 $.ajax({
		 	url: "{% url 'remove_from_cart' %}" ,
		 	data:{product_id:$( this ).attr("productid" )},
		 	type: 'post' ,
		 	success: function (data){
		 		$("#cartModal").html(data);
		 	},
		 	error: function (e){
		 		alert( "error remove-from-cart" );   
		 	}
		 })
		});
	$('#checkout-form-toggle').click(function (e) {
		 	//$('#foodcart').slideToggle(1000);
		 	
		 	$('#checkout-form').slideToggle(1000);
		 	e.preventDefault();

		 });
	$('#btn_checkout').bind("click",function(er){
			 //alert("nihamddf");
			 //alert($("#id_phone_number").val());
			 $.ajax({
			 	data:{phone_number:$("#id_phone_number").val()},
			 	type:'post',
			 	url:"{% url 'checkout_cart' %}",

			 	success: function (data){
			 		$("#cartModalBody").html(data);
			 	},
			 	error: function(e){
			 		alert( "付款出错" );   
			 	}
			 });

			})
	//$('#checkout-form').serialize()
	// $('.cart_inner').corner();
	$('#pay_offline').click();
	$('#confirm_order').on('click',  function(event) {
		event.preventDefault();
		/* Act on the event */
		var address=$('#addr_info').text();
		var send_time=$('#send_time').val();

		

		if ($("#send_time").val()=='') {
			alert("请填写发送时间");
		}else{
			if ($("#pay_offline").attr('class')=='btn btn-danger') {
				// alert('send')
				$.post("{% url 'checkout_cart'%}", {address: address,
					send_time:send_time,
					pay_way:'pay_offline'}, function(data) {
						/*optional stuff to do after success */
						// alert(data);
						data=$.parseJSON(data);
						// alert(data);
						if(data.info=='success'){
							 alert("您的订单已经成功提交，请查看");
							$('#close').click();
						};
						if(data.info=='product_0'){
							alert("您的购物车被您清空啦，再来点食物吧");
							$('#close').click();
						};
						// alert(data);
					});
			};
			if ($("#pay_online").attr('class')=='btn btn-danger') {
				// $.post("{% url 'checkout_cart'%}", {address: 'value1',
				// 	send_time:'',
				// 	pay_way:''}, function(data) {
						// optional stuff to do after success 
				// 		if(data.info=='success'){
				// 			alert("您的订单已经成功提交，请查看");
				// 		}
				// 	});
				alert("暂不支持在线付款");
			};
		};
		

	});
})
</script>
<div id="foodcart">
	{% if info %}
	<h3>{{info}}</h3>
	{% else %}
	

   <div class="modal-body" id="cartModalBody">
    
  
	<h2>您在<a href="{% url 'index' %}">{{store.name}}</a>的购物车 </h2>
	<div class="container-fluid">
		{% for product_quantity in cart.productquantities_set.all %}
		<div class="cart_product">
			<div class="product_name">{{product_quantity.product.name}}
			</div>
			<div class="cart_inner">
				<img  class="cart_product" src="{{ product_quantity.product.image.url }}"/>
			</div>

			<div class="price">
				{{ product_quantity.quantity }} X {{ product_quantity.product.price }}元
			</div>

			<a class="remove-from-cart" productid={{product_quantity.product.id}} >去除
			</a>
		</div>
		{% endfor %}
	</div>
	<HR class="hr">
		<div id="addr_panel" class="comodule-panel pointer clearfix">
			<div id="addr_div">
			<h4 class="companel-title"><i  class="icon-map-marker"></i> 送达地址：</h4>

			<div id='send_companel-content' class="companel-content">
				<span id="addr_info" class="companel-info"><p style='font-size: 16px;'>得得 18600218186 111</p>
				</span>
				<a class="companel-edit">[修改]</a>
			</div>
			</div>
			<div id="so_addr" class="cooverlay so_overlay" style="display: block;">
				<h3 class="cooverlay-header">送达地址
					<a id="addr_add" class="cooverlay-header-tip">添加新的地址</a>
				</h3>

				<ul id="addr_list" class="cooverlay-list">

					<li id="addr_new" class="addr_item coolist-item relative hide">
						<input id="newAddrRadio" class="ui-co-radio" type="radio" name="optionAddress">
						<label class="ui-co-label" for="newAddrRadio" data-id="new">
							<input class="coaddr-input addr" type="text" placeholder="外卖送到的地址">
							<input class="coaddr-input tel" type="text" placeholder="手机号码">
							<input class="coaddr-input tel-bk" type="text" placeholder="备选电话（选填）">
						</label>
						<span class="addr_action coli-action"><a class="addr_del del">×</a></span>
					</li>

					<!-- <li class="addr_item coolist-item clearfix current">
						<input id="3280347" class="ui-co-radio" type="radio" name="optionAddress" checked="checked">
						
						<label class="ui-co-label" for="3280347" data-id="3280347">
							<span class="addr">北京航空航天大11室</span>
							<span class="tel">18600218186</span>
							<span class="tel-bk"></span>
						</label>
						<span class="addr_act coli-action">
							<a class="addr_mod modify">修改</a>
							<a class="addr_del del">×</a>
							<a class="addr_sav save">保存</a>
							<a class="addr_ccl cancel">取消</a>
						</span>

					</li> -->


				</ul>

				<p style='margin-top: 5px;'>
					<button id="addr_confirm" class="btn btn-primary">保存</button>
					<button class="btn">取消</button>
				</p>


			</div>
		</div>
	<HR class="hr">
		<div id="time_panel" class="comodule-panel pointer clearfix">
			<h4 class="companel-title"><i class="icon-time"></i>送餐时间：</h4>

			 <input type="text" id="send_time" placeholder="选择送餐时间">
		</div>
	<HR class="hr">
		<div id="pay_panel" class="comodule-panel pointer clearfix">
			<h4 class="companel-title"><i class="icon-shopping-cart"></i>支付方式：</h4>

			<div class="companel-content">
				<span id="pay_info" class="companel-info">
				<a class='btn' id='pay_offline'> 餐到付款
				</a>
				<a class='btn' id='pay_online'> 在线支付
				</a>
				</span>
				
			</div>
		</div>
	<HR class="hr">
		 </div>

  <div class="modal-footer" id="cartModalfooter">
  	<div class="cart-actions">
		Total: {{cart.total}} 元
		{% if cart.products.all %} 
		<a href="#checkout" hidden class="checkout" id="checkout-form-toggle">Checkout
		</a>
		<form id="checkout-form"  
		method="post" 
		action="{% url 'checkout_cart' %}">
		<h2>Payment Information
		</h2>
		{% csrf_token %}
		{{ checkout_form.as_p }}
		<button id="btn_checkout" class="btn btn-primary">结账
		</button>
		<div class="clear"></div>
		</form>
		{% endif %}
	</div>
	<button id='confirm_order' class="btn btn-success"  aria-hidden="true">确认订单</button>
    <button id='close' class="btn" data-dismiss="modal" aria-hidden="true">关闭</button>
    
   </div>
	
	{% endif %}
</div>

src/DaZuiWang/stores/templates/index.html
{% extends 'base.html' %}

{% block body %}

<div id="store">
	
    {% for product in products %}
        <div class="product">
            {{product.name}}
            <img src="{{ product.image.url }}"/>
            <div class="description">
                {{ product.description }}
            </div>
            <div class="price">
                {{ product.price_string }}
            </div>
           
        </div>
    {% endfor %}
</div>

{% endblock %}

src/DaZuiWang/stores/templates/past_orders.html
{% extends 'base.html' %}

{% block body %}

<div id="cart">
    <h1><a href="{% url 'index' %}">{{store.name}}</a> >> Past Orders </h1>

    {% for order in orders %}
        <div class="products">
            <h2>Order #: {{ order.id }}</h2>
            {% for product_quantity in order.productquantities_set.all %}
                <div class="product">
                    {{product_quantity.product.name}}
                    <img src="{{ product_quantity.product.image.url }}"/>
                    <div class="description">
                        {{ product_quantity.product.description }}
                    </div>
                    <div class="price">
                        {{ product_quantity.quantity }} X {{ product_quantity.product.price_string }}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="cart-actions">
            Total: {{order.total}}
            {% if order.shipped_on %}
            Shipped On: {{ order.shipped_on }}
            {% endif %}
        </div>
    {% endfor %}
</div>

{% endblock %}

src/DaZuiWang/stores/templates/person_security.html
<form id="your-profile" action="/contact" method="post"> 
   {{ form.as_p }}
</form> 

src/DaZuiWang/stores/templates/products.html
	{% load staticfiles %}
{% load url from future %}

<!DOCTYPE html>
<!-- saved from url=(0042)http://www.bootcss.com/examples/hero.html# -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Bootstrap, from Twitter</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js "></script>
  
  <link href="http://cdnjs.bootcss.com/ajax/libs/twitter-bootstrap/2.3.1/css/bootstrap.css" rel="stylesheet">
  
    <!-- Le styles -->
    <script src="{% static 'bootstrap.js' %}" type="text/javascript"></script> 
    
  <link href="{% static 'datetimepicker.css' %}" rel="stylesheet">

  <script src="{% static 'bootstrap-datetimepicker.js' %}" type="text/javascript"></script>        
  <script src="{% static 'bootstrap-datetimepicker.zh-CN.js' %}" type="text/javascript"></script> 
  <script type="text/javascript" src="{% static 'bootstrap-paginator.min.js' %}"></script>
  <style type='text/css'>
  .inner{
		background-image:url({% static 'big mouth_home AD-2.png' %});
		
		background-repeat:no-repeat;
		width:270px;
		height:170px;
		position:relative;
    }
    
    .product_inner{
		background-image:url({% static 'big mouth_home AD-2.png' %});
		
		background-repeat:no-repeat;
		width:270px;
		height:170px;
		position:relative;
    }
    .store_div{
    	width:280px;
    	height:200px;
    	float:left;
    }
    img.store{
		width:187px;
		height:143px;
		position:absolute;
		left:15px;
		top:15px;
	}
	img.product{
		width:187px;
		height:143px;
		position:absolute;
		left:15px;
		top:15px;
	
	}
	.product_div{
    	width:280px;
    	height:240px;
    	float:left;
    }
	.description{
		text-align:center;
	}
	#temp{
		background-color:#ffffff;
		width:220px;
		 
	}
  </style>
	<script type="text/javascript">
	$(function(){
		
	    $('.product[productname]').bind("click" , function(e){
	    //alert($( this ).attr('productname'));
	    	var storeid=$("#storeid").attr("storeid");
	    	var storename=$("#store1").text();
	    	//alert(storeid);
	    	//alert({{store.name}});
	    	
	    	window.parent.jumpModal($( this ).attr('productname'),storename,storeid );
	    	//$('#aboutus',window.parent.document).click();
	      })  
	})	 
    </script>
</head>
    <h1 id="store1" > {{store.name}} </h1>
    <div id="storeid" width="0px" height="0px" storeid={{store.id}}></div>
	<div class="container-fluid">
	

    {% for product in store.product_set.all %}
       <div class="product_div" >
       <div class='product_inner'>
			<img class="product" productname={{product.name}} width="100px" height="100px" src="{{ product.image.url }}"/>
            </div>
			<div id="temp" class="description" text-align="left" >
				<a class="product" productname={{product.name}}> {{product.name }}</a>
			</div>			
            <div class="price">
                	价格：{{ product.price }}
            </div>
            <div>
                	库存: <span class="quantity-in-stock">{{ product.quantity }}</span>
            </div>
            </div>
      
    {% endfor %}

</div>

</html>